### ISSUE TITLE
Where's the sample?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [MFlisar/DragSelectRecyclerView#2]
All I can see in the repo is the library...
Please add the sample
:(

**Comment by MFlisar** [comment]
I don't have one. The gif is based on an app I'm developing. But I've added a demo here: https://github.com/mikepenz/FastAdapter/blob/develop/app/src/main/java/com/mikepenz/fastadapter/app/ExpandableMultiselectDeleteSampleActivity.java

It does not matter which adapter you use, the usage is very simple. The readme shows tht you just have to do 3 things.

I'll add a demo soon...

**Comment by AndroidDeveloperLB** [comment]
OK. Can you please update this post when you have a sample?

**Comment by MFlisar** [comment]
Done. Check out this repo folder: https://github.com/MFlisar/DragSelectRecyclerView/tree/master/demo/src/main/java/com/michaelflisar/dragselectrecyclerview/demo

**Comment by AndroidDeveloperLB** [comment]
I think it has a bug:
I can select items, but I can't de-select them. Not by single click, and not by dragging, like on Google Photos.

**Comment by MFlisar** [comment]
It's a very simple demo to show the usage only. Deselect all via the "Clear" button in the toolbar at the top. Normally you will add an ActionMode as well and a few other things.

Just change the onClickListener to toggle the selection if you want that. Or adjust it to whatever logic you want.

Dragging over a already selected area and dragging back will unselect the items that were already selected as well for example, this may be desired or not.

**Comment by AndroidDeveloperLB** [comment]
Can you please modify it to show that it works like on Google Photos? That de-selecting is possible via both clicking and dragging?

**Comment by MFlisar** [comment]
That's all not part of the library. That's selection logic. The library will notify you about over which items you dragged and if the range was deselected (this means, you have already dragged over those items but decided to drag back) or selected (this means the user has not yet dragged over those items and wants to select more).

What you do with this info is up to you. Remove the range from your selected items if the user does a swipe selection in a range of selected items for example. Or remember the selection you had before the drag selection started and always invert or revert the selection of the items if the item is drag selected or unselected. Do whatever you want, it's totally up to you.

This library does not provide selection or anything like this, just the events of the drag selector. As said, you can implement any logic with this...

I changed the demo to toggle the selection if you click an item, but the rest is up to you and up to your personal needs.

**Comment by AndroidDeveloperLB** [comment]
ok, sorry and thanks. I just thought it would be a more fitting and whole sample if it showed that it can do exactly as the original app.

**Comment by MFlisar** [comment]
If you define the behaviour I can show you how to achieve it...

**Comment by AndroidDeveloperLB** [comment]
I was only curious to see a library that works like on Google Photos. I don't need it currently. Was just searching for something interesting. I even asked about it here:
http://stackoverflow.com/q/41199611/878126

**Comment by MFlisar** [comment]
I tried google photos. It does react the same way as my demo, you can't deselect items via drag selection....

I could think of the ability to start selection mode by long pressing a not selected items and starting a desolation mode by long pressing an already selected item. That should be quite easy to achieve

**Comment by AndroidDeveloperLB** [comment]
On Google Photos, you can deselect items, even by dragging, though by dragging it works in a bit weird way.
To reproduce, select multiple items (use dragging if you wish). Then, drag an already selected item to selected items, go back and then again to those items. Now it's deselecting them.

What you offer seems better. To drag an already selected item to start deselection...

**Comment by MFlisar** [comment]
This is working in my demo as well. That's because the logic is kept simple - dragging back means unselected and dragging away from the first selected item means select. No logic for remembering the original state.

**Comment by AndroidDeveloperLB** [comment]
Correct. Thought it didn't have it. 
But what you offered is better I think.
Also, single click should de-select, as we both mentioned.

**Comment by MFlisar** [comment]
Single click worked as well already, it toggles the selection...

I extended the DragSelectListener a little bit and added an `OnAdvancedDragSelectListener` and updated the demo, it shows you how to use it with 3 different modes.

**Comment by AndroidDeveloperLB** [comment]
Nice. Thank you.
What's the difference between "advanced" and the "advanced first item dependant" (typo btw, should be dependent)  ?

**Comment by MFlisar** [comment]
Try it ;-).

There are some comments in the demo.

Advanced will invert the initial state on drag selection and revert to the
original state if you drag back. It will just toggle any item and revert to
initial state if you drag back.

The other one will do the same as happened to the first item to all others
and simple do the inverse on drag back. This means if you long press an
unselected item each drag selected item will be unselected as well, if you
drag back each item will be selected. And vice versa...

AndroidDeveloperLB <notifications@github.com> schrieb am Sa., 4. März 2017,
11:38:

**Comment by AndroidDeveloperLB** [comment]
Ohh....
Both seem logical things to choose from. Thank you.
So in other words:
Advanced :  will toggle each item you go by, no matter what is the first item.
advanced first item dependent -If first was selected, now it goes to deselection mode on all. and the opposite.

**Comment by MFlisar** [comment]
Exactly

**Comment by MFlisar** [comment]
I think I'll add a reusable helper class to the library and even add a fourth mode, a combination of the second and third mode...

Any naming suggestions for the 3 modes?

**Comment by AndroidDeveloperLB** [comment]
I think you can just add a TextView above the RecyclerView, saying how the current mode works.
But, here are mine:
1. simple -> drag to select
2. advanced -> drag to toggle all in the way
3. advanced first item dependent - drag to toggle from first item

**Comment by MFlisar** [comment]
Naming for the demo is not that important. I want to provide a configurable class that can be used in any project with any adapter, therefore this must be configurable with a mode and for this mode I need names...

Maybe 

    enum Mode
    {
        /* simply selects each items you go by, unselects on move back */
        Simple,
        /* toggles each items original state, reverts to the original state on move back */
        Toggle, // or ToggleAndRememberOriginalState
        /* toggles the first item and applies the same state to each item you go by and inverted state on move back */
        FirstItemDependent, // or ???
        /* toggles the item and applies the same state to each item you go by and reverts to the original state on move back */
        FirstItemDependentToggle  // or FirstItemDependentToggleAndRememberOriginalState
    }

**Comment by AndroidDeveloperLB** [comment]
Sure. 
Just please use javadocs instead of comments (meaning "/** this */ "  instead of "// this"

**Comment by MFlisar** [comment]
You can check out the new demo, it uses a so called `DragSelectionProcessor` and offers all 4 modes and is useable via a very simple setup and just replaces the `OnDragSelectListener`.

It does do all the logic for you, you just have to select/deselect items if the processor tell you to do so and that's it.

**Comment by AndroidDeveloperLB** [comment]
Thank you so much.
You are welcomed to try out my tiny libraries and apps, if you wish:
https://github.com/AndroidDeveloperLB?tab=repositories
https://play.google.com/store/apps/developer?id=AndroidDeveloperLB

**Comment by MFlisar** [comment]
I've checked them already ;-)
